import Head from 'next/head'
import Link from 'next/link'
import { Box, Card, CardContent, Typography, Button } from '@mui/material'
import Movie from '../models/Movie'
import connectDb from '../lib/dbConnect'

export default function Home({movies}) {
  console.log(movies)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box 
        sx={{
          margin: "2rem 5rem"
        }}
      >
        <Typography variant='h3'>
          Movies
        </Typography>

        <Link href="/new">
          <a>
            <Button
              variant='contained'
              color='primary'
            >Agregar</Button>
          </a>
        </Link>

        {
          movies.map(({_id, title, plot}) => (
            <Card sx={{ minWidth: 275, maxWidth:500 }} key={_id}>
              <CardContent>
                <Typography variant='h5'>
                  {title}
                </Typography>
                <Typography variant='body1'>
                  {plot}
                </Typography>
                <Button>
                  <Link href={`/${_id}`}>
                    <a>Más información</a>
                  </Link>
                </Button>
              </CardContent>
            </Card>
          ))
        }
        
      </Box>
    </div>
  )
}

export async function getServerSideProps(){
  try {
    await connectDb()

    const res = await Movie.find({})

    // Se cambia el formato "extraño" del id de cada documento por un String

    const movies = res.map(doc => {
      const movie = doc.toObject()
      movie._id = `${movie._id}`
      return movie
    })

    return {props: {movies}} 

  } catch (error) {

    console.log(error)
  }
}